# Shared mutual fund scheme details matching ArthaAI UI and factsheet specs
FUND_DATA = {
    "sbi_bluechip": {
        "name": "SBI Bluechip Fund Direct Growth",
        "category": "Equity - Large Cap",
        "nav": "₹ 92.41",
        "change": "+0.12% (1D)",
        "change_positive": True,
        "aum": "₹ 48,926 Cr",
        "expense_ratio": "0.85%",
        "manager": "Mr. Saurabh Pant",
        "min_sip": "₹ 500",
        "riskometer": "Very High Risk",
        "return_1y": "26.8%",
        "return_3y": "16.2%",
        "return_5y": "17.5%",
        "holdings": [
            ("HDFC Bank Ltd", "Financial Services", "9.05%"),
            ("ICICI Bank Ltd", "Financial Services", "8.10%"),
            ("Reliance Industries Ltd", "Energy / Oil & Gas", "6.73%"),
            ("Larsen & Toubro Ltd", "Construction", "5.30%"),
            ("State Bank of India", "Financial Services", "3.82%"),
            ("Asian Paints Ltd", "Consumer Durables", "3.67%"),
            ("HDFC Life Insurance Company Ltd", "Financial Services", "3.50%"),
            ("Infosys Ltd", "Technology", "3.43%"),
            ("Kotak Mahindra Bank Ltd", "Financial Services", "3.32%"),
            ("Axis Bank Ltd", "Financial Services", "3.26%"),
            ("Tata Motors Ltd", "Automobile And Auto Components", "3.07%"),
            ("Bharti Airtel Ltd", "Telecommunication", "2.66%"),
            ("Avenue Supermarts Ltd", "Consumer Services", "2.49%"),
            ("Samvardhana Motherson International Ltd", "Automobile And Auto Components", "2.47%"),
            ("Divi's Laboratories Ltd", "Healthcare", "2.47%"),
            ("Page Industries Ltd", "Textiles", "2.06%"),
            ("Thermax Ltd", "Capital Goods", "1.93%"),
            ("Varun Beverages Ltd", "Fast Moving Consumer Goods", "1.92%"),
            ("Tech Mahindra Ltd", "Technology", "1.84%"),
            ("Tata Steel Ltd", "Metals & Mining", "1.84%"),
            ("Cholamandalam Investment & Finance Co Ltd", "Financial Services", "1.83%"),
            ("Shree Cements Ltd", "Construction Materials", "1.79%"),
            ("Mankind Pharma Ltd", "Healthcare", "1.67%"),
            ("Hindustan Unilever Ltd", "Fast Moving Consumer Goods", "1.43%"),
            ("Vedanta Ltd", "Metals & Mining", "1.41%"),
            ("Eternal Ltd", "Consumer Durables", "1.36%"),
            ("Hindalco Industries Ltd", "Metals & Mining", "1.33%"),
            ("Sun Pharmaceutical Industries Ltd", "Healthcare", "1.22%"),
            ("ICICI Prudential Asset Management Company Ltd", "Financial Services", "1.16%"),
            ("ICICI Prudential Life Insurance Company Ltd", "Financial Services", "1.05%"),
            ("Schaeffler India Ltd", "Capital Goods", "1.03%"),
            ("Sona Blw Precision Forgings Ltd", "Automobile And Auto Components", "0.98%"),
            ("Britannia Industries Ltd", "Fast Moving Consumer Goods", "0.96%"),
            ("Eicher Motors Ltd", "Automobile And Auto Components", "0.91%"),
            ("Interglobe Aviation Ltd", "Consumer Services", "0.89%"),
            ("ICICI Lombard General Insurance Company Ltd", "Financial Services", "0.89%"),
            ("Brainbees Solutions Ltd", "Consumer Services", "0.86%"),
            ("GAIL (India) Ltd", "Energy / Oil & Gas", "0.82%"),
            ("PI Industries Ltd", "Chemicals", "0.63%"),
            ("Motherson Sumi Wiring India Ltd", "Automobile And Auto Components", "0.50%"),
            ("SKF India (Industrial) Ltd", "Capital Goods", "0.34%"),
            ("SKF India Ltd", "Capital Goods", "0.23%"),
            ("Cipla Ltd", "Healthcare", "0.18%"),
            ("Bharat Petroleum Corporation Ltd", "Energy / Oil & Gas", "0.06%"),
            ("Kwality Walls India Ltd", "Fast Moving Consumer Goods", "0.02%")
        ],
        "desc": "Invests predominantly in large-cap stocks for long-term capital growth."
    },
    "parag_parikh_flexi": {
        "name": "Parag Parikh Flexi Cap Fund Direct Growth",
        "category": "Equity - Flexi Cap",
        "nav": "₹ 84.62",
        "change": "+0.42% (1D)",
        "change_positive": True,
        "aum": "₹ 1,40,949 Cr",
        "expense_ratio": "0.55%",
        "manager": "Mr. Rajeev Thakkar",
        "min_sip": "₹ 1,000",
        "riskometer": "Very High Risk",
        "return_1y": "4.44%",
        "return_3y": "17.64%",
        "return_5y": "16.80%",
        "holdings": [
            ("HDFC Bank Ltd", "Financial Services", "7.94%"),
            ("Power Grid Corporation of India Ltd", "Energy / Oil & Gas", "6.99%"),
            ("Coal India Ltd", "Energy / Oil & Gas", "5.95%"),
            ("ITC Ltd", "Fast Moving Consumer Goods", "5.43%"),
            ("ICICI Bank Ltd", "Financial Services", "4.92%"),
            ("Bajaj Holdings & Investment Ltd", "Financial Services", "4.41%"),
            ("Kotak Mahindra Bank Ltd", "Financial Services", "4.03%"),
            ("Mahindra & Mahindra Ltd", "Automobile And Auto Components", "3.52%"),
            ("HCL Technologies Ltd", "Technology", "3.43%"),
            ("Infosys Ltd", "Technology", "3.03%"),
            ("Axis Bank Ltd", "Financial Services", "2.99%"),
            ("Maruti Suzuki India Ltd", "Automobile And Auto Components", "2.87%"),
            ("Bharti Airtel Ltd", "Telecommunication", "2.83%"),
            ("Tata Consultancy Services Ltd", "Technology", "2.79%"),
            ("Dr. Reddy's Laboratories Ltd", "Healthcare", "1.34%"),
            ("Cipla Ltd", "Healthcare", "1.33%"),
            ("Zydus Lifesciences Ltd", "Healthcare", "1.21%"),
            ("Zydus Wellness Ltd", "Fast Moving Consumer Goods", "0.80%"),
            ("Indian Energy Exchange Ltd", "Financial Services", "0.72%"),
            ("EID Parry India Ltd", "Fast Moving Consumer Goods", "0.49%"),
            ("Indraprastha Gas Ltd", "Energy / Oil & Gas", "0.45%"),
            ("Narayana Hrudayalaya Ltd", "Healthcare", "0.25%"),
            ("The Great Eastern Shipping Company Ltd", "Consumer Services", "0.25%"),
            ("Central Depository Services (India) Ltd", "Financial Services", "0.20%"),
            ("CMS Info Systems Ltd", "Consumer Services", "0.14%"),
            ("ICRA Ltd", "Financial Services", "0.11%"),
            ("Maharashtra Scooters Ltd", "Financial Services", "0.07%"),
            ("Mahanagar Gas Ltd", "Energy / Oil & Gas", "0.03%"),
            ("Indus Towers Ltd", "Telecommunication", "0.03%"),
            ("CIE Automotive India Ltd", "Automobile And Auto Components", "0.02%"),
            ("Swaraj Engines Ltd", "Capital Goods", "0.01%"),
            ("Nesco Ltd", "Consumer Services", "0.01%"),
            ("Alphabet Inc A", "Technology / Internet", "4.90%"),
            ("Amazon.com Inc", "Technology / Internet", "2.47%"),
            ("Meta Platforms Inc", "Technology / Internet", "2.44%"),
            ("Microsoft Corp", "Technology", "2.01%"),
            ("Embassy Office Parks REIT", "Real Estate", "2.51%"),
            ("Brookfield India REIT", "Real Estate", "1.54%"),
            ("Mindspace Business Parks REIT", "Real Estate", "0.03%"),
            ("Parag Parikh Liquid Fund", "Debt / Cash", "0.46%")
        ],
        "desc": "Dynamically invests across cap sizes, with up to 35% exposure in global stocks like Alphabet and Amazon."
    },
    "hdfc_top100": {
        "name": "HDFC Top 100 Fund Direct Growth",
        "category": "Equity - Large Cap",
        "nav": "₹ 112.56",
        "change": "+0.35% (1D)",
        "change_positive": True,
        "aum": "₹ 38,121 Cr",
        "expense_ratio": "0.90%",
        "manager": "Mr. Rahul Baijal",
        "min_sip": "₹ 500",
        "riskometer": "Very High Risk",
        "return_1y": "29.2%",
        "return_3y": "18.5%",
        "return_5y": "16.2%",
        "holdings": [
            ("ICICI Bank Ltd", "Financial Services", "9.15%"),
            ("HDFC Bank Ltd", "Financial Services", "7.84%"),
            ("Bharti Airtel Ltd", "Telecommunication", "5.90%"),
            ("Reliance Industries Ltd", "Energy / Oil & Gas", "5.61%"),
            ("Kotak Mahindra Bank Ltd", "Financial Services", "5.47%"),
            ("Titan Company Ltd", "Consumer Durables", "4.74%"),
            ("Axis Bank Ltd", "Financial Services", "3.56%"),
            ("Torrent Pharmaceuticals Ltd", "Healthcare", "3.49%"),
            ("Infosys Ltd", "Technology", "3.01%"),
            ("Bajaj Auto Ltd", "Automobile And Auto Components", "2.95%")
        ],
        "desc": "A conservative scheme focusing on bluechip companies and market leaders."
    },
    "icici_prudential": {
        "name": "ICICI Prudential Bluechip Fund Direct Growth",
        "category": "Equity - Large Cap",
        "nav": "₹ 104.28",
        "change": "-0.15% (1D)",
        "change_positive": False,
        "aum": "₹ 75,650 Cr",
        "expense_ratio": "0.70%",
        "manager": "Mr. Anish Tawakley",
        "min_sip": "₹ 100",
        "riskometer": "Very High Risk",
        "return_1y": "0.07%",
        "return_3y": "15.26%",
        "return_5y": "14.67%",
        "holdings": [
            ("Hindustan Aeronautics Ltd", "Capital Goods", "1.13%"),
            ("Maruti Suzuki India Ltd", "Automobile And Auto Components", "3.78%"),
            ("Mahindra & Mahindra Ltd", "Automobile And Auto Components", "2.40%"),
            ("Hero Motocorp Ltd", "Automobile And Auto Components", "1.86%"),
            ("Hyundai Motor India Ltd", "Automobile And Auto Components", "0.95%"),
            ("Bajaj Auto Ltd", "Automobile And Auto Components", "0.60%"),
            ("HDFC Bank Ltd", "Financial Services", "8.85%"),
            ("ICICI Bank Ltd", "Financial Services", "8.84%"),
            ("Axis Bank Ltd", "Financial Services", "4.63%"),
            ("HDFC Asset Management Company Ltd", "Financial Services", "0.67%"),
            ("Ultratech Cement Ltd", "Construction Materials", "2.81%"),
            ("Shree Cements Ltd", "Construction Materials", "0.74%"),
            ("Larsen & Toubro Ltd", "Construction", "5.66%"),
            ("Asian Paints Ltd", "Consumer Durables", "2.31%"),
            ("ITC Ltd", "Fast Moving Consumer Goods", "1.04%"),
            ("Siemens Ltd", "Capital Goods", "0.77%"),
            ("Cummins India Ltd", "Capital Goods", "0.82%"),
            ("SBI Life Insurance Company Ltd", "Financial Services", "1.18%"),
            ("HDFC Life Insurance Company Ltd", "Financial Services", "1.04%"),
            ("ICICI Prudential Life Insurance Company Ltd", "Financial Services", "1.02%"),
            ("Infosys Ltd", "Technology", "3.94%"),
            ("HCL Technologies Ltd", "Technology", "0.91%"),
            ("Wipro Ltd", "Technology", "0.60%"),
            ("Tech Mahindra Ltd", "Technology", "0.60%"),
            ("Oil & Natural Gas Corporation Ltd", "Energy / Oil & Gas", "1.34%"),
            ("Procter & Gamble Hygiene and Health Care Ltd", "Fast Moving Consumer Goods", "0.71%"),
            ("Reliance Industries Ltd", "Energy / Oil & Gas", "5.62%"),
            ("Bharat Petroleum Corporation Ltd", "Energy / Oil & Gas", "0.66%"),
            ("Sun Pharmaceutical Industries Ltd", "Healthcare", "2.69%"),
            ("NTPC Ltd", "Energy / Oil & Gas", "2.48%"),
            ("Power Grid Corporation of India Ltd", "Energy / Oil & Gas", "1.35%"),
            ("Tata Power Company Ltd", "Energy / Oil & Gas", "0.83%"),
            ("DLF Ltd", "Real Estate", "1.32%"),
            ("Avenue Supermarts Ltd", "Consumer Services", "0.87%"),
            ("Trent Ltd", "Consumer Services", "0.68%"),
            ("Eternal Ltd", "Consumer Durables", "0.61%"),
            ("Bharti Airtel Ltd", "Telecommunication", "4.43%"),
            ("Page Industries Ltd", "Textiles", "0.60%"),
            ("Interglobe Aviation Ltd", "Consumer Services", "1.80%")
        ],
        "desc": "Focuses on established large-cap leaders with strong balance sheets and lower relative volatility."
    },
    "mirae_asset": {
        "name": "Mirae Asset Large Cap Fund Direct Growth",
        "category": "Equity - Large Cap",
        "nav": "₹ 98.65",
        "change": "+0.22% (1D)",
        "change_positive": True,
        "aum": "₹ 38,239 Cr",
        "expense_ratio": "0.65%",
        "manager": "Mr. Gaurav Misra",
        "min_sip": "₹ 500",
        "riskometer": "Very High Risk",
        "return_1y": "0.67%",
        "return_3y": "11.06%",
        "return_5y": "10.74%",
        "holdings": [
            ("HDFC Bank Ltd", "Financial Services", "9.15%"),
            ("ICICI Bank Ltd", "Financial Services", "8.12%"),
            ("Reliance Industries Ltd", "Energy / Oil & Gas", "5.76%"),
            ("Bharti Airtel Ltd", "Telecommunication", "4.99%"),
            ("Infosys Ltd", "Technology", "4.09%"),
            ("Larsen & Toubro Ltd", "Construction", "3.47%"),
            ("State Bank of India", "Financial Services", "3.42%"),
            ("Axis Bank Ltd", "Financial Services", "3.37%"),
            ("ITC Ltd", "Fast Moving Consumer Goods", "2.83%"),
            ("Eternal Ltd", "Consumer Durables", "2.48%")
        ],
        "desc": "Aims for capital growth through quality large-cap companies with robust growth trajectories."
    }
}
