# Shared mutual fund scheme details matching ArthaAI UI and factsheet specs
FUND_DATA = {
    "parag_parikh_flexi": {
        "name": "Parag Parikh Flexi Cap Fund Direct Growth",
        "category": "Equity - Flexi Cap",
        "nav": "₹ 84.62",
        "change": "+0.42% (1D)",
        "change_positive": True,
        "aum": "₹ 1,40,949 Cr",
        "expense_ratio": "0.55%",
        "manager": "Mr. Rajeev Thakkar",
        "min_sip": "₹ 1,000",
        "riskometer": "Very High Risk",
        "return_1y": "34.4%",
        "return_3y": "17.6%",
        "return_5y": "16.8%",
        "holdings": [
            ("HDFC Bank Ltd", "Financial Services", "7.94%"),
            ("Power Grid Corporation of India Ltd", "Energy / Oil & Gas", "6.99%"),
            ("Coal India Ltd", "Energy / Oil & Gas", "5.95%"),
            ("ITC Ltd", "Fast Moving Consumer Goods", "5.43%"),
            ("ICICI Bank Ltd", "Financial Services", "4.92%"),
            ("Bajaj Holdings & Investment Ltd", "Financial Services", "4.41%"),
            ("Kotak Mahindra Bank Ltd", "Financial Services", "4.03%"),
            ("Mahindra & Mahindra Ltd", "Automobile And Auto Components", "3.52%"),
            ("HCL Technologies Ltd", "Technology", "3.43%"),
            ("Infosys Ltd", "Technology", "3.03%"),
            ("Axis Bank Ltd", "Financial Services", "2.99%"),
            ("Maruti Suzuki India Ltd", "Automobile And Auto Components", "2.87%"),
            ("Bharti Airtel Ltd", "Telecommunication", "2.83%"),
            ("Tata Consultancy Services Ltd", "Technology", "2.79%"),
            ("Dr. Reddy's Laboratories Ltd", "Healthcare", "1.34%"),
            ("Cipla Ltd", "Healthcare", "1.33%"),
            ("Zydus Lifesciences Ltd", "Healthcare", "1.21%"),
            ("Zydus Wellness Ltd", "Fast Moving Consumer Goods", "0.80%"),
            ("Indian Energy Exchange Ltd", "Financial Services", "0.72%"),
            ("EID Parry India Ltd", "Fast Moving Consumer Goods", "0.49%"),
            ("Indraprastha Gas Ltd", "Energy / Oil & Gas", "0.45%"),
            ("Narayana Hrudayalaya Ltd", "Healthcare", "0.25%"),
            ("The Great Eastern Shipping Company Ltd", "Consumer Services", "0.25%"),
            ("Central Depository Services (India) Ltd", "Financial Services", "0.20%"),
            ("CMS Info Systems Ltd", "Consumer Services", "0.14%"),
            ("ICRA Ltd", "Financial Services", "0.11%"),
            ("Maharashtra Scooters Ltd", "Financial Services", "0.07%"),
            ("Mahanagar Gas Ltd", "Energy / Oil & Gas", "0.03%"),
            ("Indus Towers Ltd", "Telecommunication", "0.03%"),
            ("CIE Automotive India Ltd", "Automobile And Auto Components", "0.02%"),
            ("Swaraj Engines Ltd", "Capital Goods", "0.01%"),
            ("Nesco Ltd", "Consumer Services", "0.01%"),
            ("Alphabet Inc A", "Technology / Internet", "4.90%"),
            ("Amazon.com Inc", "Technology / Internet", "2.47%"),
            ("Meta Platforms Inc", "Technology / Internet", "2.44%"),
            ("Microsoft Corp", "Technology", "2.01%"),
            ("Embassy Office Parks REIT", "Real Estate", "2.51%"),
            ("Brookfield India REIT", "Real Estate", "1.54%"),
            ("Mindspace Business Parks REIT", "Real Estate", "0.03%"),
            ("Parag Parikh Liquid Fund", "Debt / Cash", "0.46%")
        ],
        "desc": "Dynamically invests across cap sizes, with up to 35% exposure in global stocks like Alphabet and Amazon."
    },
    "pp_tax_saver": {
        "name": "Parag Parikh ELSS Tax Saver Fund Direct Growth",
        "category": "Equity - ELSS (Tax Saver)",
        "nav": "₹ 34.12",
        "change": "+0.38% (1D)",
        "change_positive": True,
        "aum": "₹ 5,617 Cr",
        "expense_ratio": "0.60%",
        "manager": "Mr. Rajeev Thakkar",
        "min_sip": "₹ 500",
        "riskometer": "Very High Risk",
        "return_1y": "32.8%",
        "return_3y": "16.5%",
        "return_5y": "16.1%",
        "holdings": [
            ("HDFC Bank Ltd", "Financial Services", "8.20%"),
            ("Power Grid Corporation of India Ltd", "Energy / Oil & Gas", "7.15%"),
            ("Coal India Ltd", "Energy / Oil & Gas", "6.10%"),
            ("ITC Ltd", "Fast Moving Consumer Goods", "5.80%"),
            ("ICICI Bank Ltd", "Financial Services", "5.10%"),
            ("Bajaj Holdings & Investment Ltd", "Financial Services", "4.50%"),
            ("Kotak Mahindra Bank Ltd", "Financial Services", "4.10%"),
            ("Mahindra & Mahindra Ltd", "Automobile And Auto Components", "3.60%"),
            ("HCL Technologies Ltd", "Technology", "3.50%"),
            ("Infosys Ltd", "Technology", "3.10%"),
            ("Axis Bank Ltd", "Financial Services", "3.00%"),
            ("Maruti Suzuki India Ltd", "Automobile And Auto Components", "2.90%"),
            ("Tata Consultancy Services Ltd", "Technology", "2.80%"),
            ("Dr. Reddy's Laboratories Ltd", "Healthcare", "1.40%"),
            ("Cipla Ltd", "Healthcare", "1.35%"),
            ("Zydus Lifesciences Ltd", "Healthcare", "1.25%")
        ],
        "desc": "An equity-linked savings scheme focusing on long-term capital growth with a statutory 3-year lock-in period."
    },
    "pp_conservative": {
        "name": "Parag Parikh Conservative Hybrid Fund Direct Growth",
        "category": "Hybrid - Conservative Hybrid",
        "nav": "₹ 15.24",
        "change": "+0.05% (1D)",
        "change_positive": True,
        "aum": "₹ 3,344 Cr",
        "expense_ratio": "0.32%",
        "manager": "Mr. Raj Mehta",
        "min_sip": "₹ 1,000",
        "riskometer": "Moderately High Risk",
        "return_1y": "9.5%",
        "return_3y": "9.9%",
        "return_5y": "9.4%",
        "holdings": [
            ("7.18% Government Securities 2026", "Sovereign Debt", "15.40%"),
            ("7.26% Government Securities 2029", "Sovereign Debt", "12.80%"),
            ("State Development Loans - Tamilnadu", "Sovereign Debt", "8.50%"),
            ("State Development Loans - Gujarat", "Sovereign Debt", "7.20%"),
            ("Embassy Office Parks REIT", "Real Estate", "5.20%"),
            ("Brookfield India Real Estate Trust REIT", "Real Estate", "4.10%"),
            ("HDFC Bank Ltd", "Financial Services", "2.80%"),
            ("ICICI Bank Ltd", "Financial Services", "2.40%"),
            ("Power Grid Corporation of India Ltd", "Energy / Oil & Gas", "2.10%"),
            ("Coal India Ltd", "Energy / Oil & Gas", "1.95%"),
            ("ITC Ltd", "Fast Moving Consumer Goods", "1.80%")
        ],
        "desc": "Focuses on generating regular income through G-Secs and debt instruments, with a small portion in equity and REITs."
    },
    "pp_liquid": {
        "name": "Parag Parikh Liquid Fund Direct Growth",
        "category": "Debt - Liquid Fund",
        "nav": "₹ 62.45",
        "change": "+0.02% (1D)",
        "change_positive": True,
        "aum": "₹ 5,260 Cr",
        "expense_ratio": "0.09%",
        "manager": "Mr. Raj Mehta",
        "min_sip": "₹ 1,000",
        "riskometer": "Low to Moderate Risk",
        "return_1y": "6.1%",
        "return_3y": "6.7%",
        "return_5y": "5.5%",
        "holdings": [
            ("Triparty Repo (TREPS)", "Cash & Short-Term Debt", "35.50%"),
            ("91-Day Treasury Bills", "Sovereign Debt", "20.40%"),
            ("182-Day Treasury Bills", "Sovereign Debt", "15.20%"),
            ("364-Day Treasury Bills", "Sovereign Debt", "12.80%"),
            ("Small Industries Development Bank of India CD", "Commercial Paper / CDs", "6.10%"),
            ("NABARD Commercial Paper", "Commercial Paper / CDs", "5.40%"),
            ("Union Bank of India CD", "Commercial Paper / CDs", "4.60%")
        ],
        "desc": "Invests in highly liquid, high-quality, short-term debt and money market securities for cash parking."
    },
    "pp_dynamic": {
        "name": "Parag Parikh Dynamic Asset Allocation Fund Direct Growth",
        "category": "Hybrid - Dynamic Asset Allocation",
        "nav": "₹ 11.20",
        "change": "+0.08% (1D)",
        "change_positive": True,
        "aum": "₹ 2,709 Cr",
        "expense_ratio": "0.27%",
        "manager": "Mr. Rajeev Thakkar",
        "min_sip": "₹ 1,000",
        "riskometer": "High Risk",
        "return_1y": "2.6%",
        "return_3y": "2.6%",
        "return_5y": "2.6%",
        "holdings": [
            ("State Development Loans - Karnataka", "Sovereign Debt", "14.50%"),
            ("State Development Loans - Maharashtra", "Sovereign Debt", "12.10%"),
            ("7.06% Government Securities 2028", "Sovereign Debt", "10.80%"),
            ("Parag Parikh Liquid Fund - Direct Growth", "Debt Mutual Fund", "9.50%"),
            ("Embassy Office Parks REIT", "Real Estate", "5.80%"),
            ("Brookfield India Real Estate Trust REIT", "Real Estate", "4.60%"),
            ("HDFC Bank Ltd", "Financial Services", "4.10%"),
            ("ICICI Bank Ltd", "Financial Services", "3.80%"),
            ("ITC Ltd", "Fast Moving Consumer Goods", "2.40%"),
            ("Coal India Ltd", "Energy / Oil & Gas", "1.90%")
        ],
        "desc": "Dynamically shifts asset allocation between equity, derivatives, and fixed-income depending on market valuations."
    }
}
